// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwgwqhzeozukhnyeqdvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Z3dxaHplb3p1a2hueWVxZHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MDgwMTIsImV4cCI6MjA1MTk4NDAxMn0.zJ1IXz7SESW89HeiB7OML0kuTZ8ESlpERGstAokWRHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);